import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./component/header/Header";
import { Footer } from "./component/footer/Footer";
import Main from "./component/main/Main";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const apiKey = process.env.NEXT_PUBLIC_MOVIEDB_API_KEY;
const baseUrl = process.env.TMDB_BASE_URL;
console.log(`API Key: ${apiKey}, Base URL: ${baseUrl}`);
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header/>
        <Main/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
